---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/supersam.minetest.ch
  tasks:
    - name: Checkout git
      ansible.builtin.git:
        repo: https://github.com/BuckarooBanzay/supersam.minetest.ch
        dest: "{{ compose_directory }}"
        single_branch: yes
        force: yes
        version: main

    - name: Template files
      with_list:
       - "minetest.conf"
       - "matterbridge.toml"
       - "docker-compose.yml"
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"

    - name: Create and start services
      shell:
        cmd: "docker-compose up -d --remove-orphans"
        chdir: "{{ compose_directory }}"
