version: "2"

services:
 minetest:
  image: ghcr.io/minetest/minetest:5.10.0
  restart: always
  user: root
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
   - "./minetest.conf:/minetest.conf"
  ports:
   - "30002:30002/udp"
  networks:
   - terminator
   - default
  command: ["--config", "/minetest.conf"]

 matterbridge:
   image: 42wim/matterbridge:1.26.0
   dns:
    - 8.8.4.4
    - 8.8.8.8
   volumes:
    - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
    - ./remotenickformat.tengo:/remotenickformat.tengo

 supersam-lab-ui:
  image: ghcr.io/minetest-go/mtui:v1.79
  networks:
   - terminator
   - default
  environment:
   COOKIE_DOMAIN: "supersam.luanti.ch"
   COOKIE_SECURE: "true"
   LOGLEVEL: debug
   WORLD_DIR: "/root/.minetest/worlds/world"
   API_KEY: "{{mtui_key}}"
   ENABLE_FEATURES: "shell,luashell,monitoring,xban,modmanagement"
   SERVER_NAME: "Super sam"
   MINETEST_CONFIG: "/minetest.conf"
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
   - "./minetest.conf:/minetest.conf"
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.supersam-luanti-ch.rule=Host(`supersam.luanti.ch`)"
    - "traefik.http.services.supersam-luanti-ch.loadbalancer.server.port=8080"
    - "traefik.http.routers.supersam-luanti-ch.entrypoints=websecure"
    - "traefik.http.routers.supersam-luanti-ch.tls.certresolver=default"

 redirect:
  image: nginx:1.27.3
  networks:
   - terminator
   - default
  restart: always
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.supersam-minetest-ch.rule=Host(`supersam.minetest.ch`)"
    - "traefik.http.services.supersam-minetest-ch.loadbalancer.server.port=80"
    - "traefik.http.routers.supersam-minetest-ch.entrypoints=websecure"
    - "traefik.http.routers.supersam-minetest-ch.tls.certresolver=default"
  volumes:
   - "./redirect.conf:/etc/nginx/conf.d/default.conf:ro"

networks:
 terminator:
  external: true
