version: "2"

services:
 minetest:
  image: ghcr.io/minetest-hosting/minetest-docker:5.8.0
  restart: always
  user: root
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./game:/root/.minetest/worlds/world/game"
   - "./.git:/root/.minetest/worlds/world/git_info:ro"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
   - "./worldmods:/root/.minetest/worlds/world/worldmods"
   - "./minetest.conf:/minetest.conf"
  labels:
   - "promtail=true"
  ports:
    - "30002:30002/udp"
  networks:
   - terminator
   - default
  entrypoint: ["minetestserver", "--config", "/minetest.conf"]

 matterbridge:
   image: 42wim/matterbridge:1.26.0
   dns:
    - 8.8.4.4
    - 8.8.8.8
   labels:
    - "promtail=true"
   volumes:
    - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
    - ./remotenickformat.tengo:/remotenickformat.tengo

 supersam-lab-ui:
  image: ghcr.io/minetest-go/mtui:1.58
  networks:
   - terminator
   - default
  environment:
   COOKIE_DOMAIN: "supersam.minetest.ch"
   COOKIE_SECURE: "true"
   LOGLEVEL: debug
   WORLD_DIR: "/root/.minetest/worlds/world"
   API_KEY: "{{mtui_key}}"
   ENABLE_FEATURES: "shell,luashell,monitoring,xban"
   SERVER_NAME: "Super sam"
   MINETEST_CONFIG: "/minetest.conf"
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./game:/root/.minetest/worlds/world/game"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
   - "./worldmods:/root/.minetest/worlds/world/worldmods"
   - "./minetest.conf:/minetest.conf"
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.supersam.rule=Host(`supersam.minetest.ch`)"
    - "traefik.http.services.supersam.loadbalancer.server.port=8080"
    - "traefik.http.routers.supersam.entrypoints=websecure"
    - "traefik.http.routers.supersam.tls.certresolver=default"

networks:
 terminator:
  external: true
